src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $catchPhrase = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(nullable: true)]
    private array $related_subjects = [];

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    private ?string $chapo = null;

    #[ORM\Column(length: 255)]
    private ?string $legendMainPicture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $authorWebsite = null;

    #[ORM\Column(nullable: true)]
    private ?int $relatedCourse = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCatchPhrase(): ?string
    {
        return $this->catchPhrase;
    }

    public function setCatchPhrase(string $catchPhrase): self
    {
        $this->catchPhrase = $catchPhrase;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getRelatedSubjects(): array
    {
        return $this->related_subjects;
    }

    public function setRelatedSubjects(?array $related_subjects): self
    {
        $this->related_subjects = $related_subjects;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getChapo(): ?string
    {
        return $this->chapo;
    }

    public function setChapo(string $chapo): self
    {
        $this->chapo = $chapo;

        return $this;
    }

    public function getLegendMainPicture(): ?string
    {
        return $this->legendMainPicture;
    }

    public function setLegendMainPicture(string $legendMainPicture): self
    {
        $this->legendMainPicture = $legendMainPicture;

        return $this;
    }

    public function getAuthorWebsite(): ?string
    {
        return $this->authorWebsite;
    }

    public function setAuthorWebsite(?string $authorWebsite): self
    {
        $this->authorWebsite = $authorWebsite;

        return $this;
    }

    public function getRelatedCourse(): ?int
    {
        return $this->relatedCourse;
    }

    public function setRelatedCourse(?int $relatedCourse): self
    {
        $this->relatedCourse = $relatedCourse;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function __toString(){
    return  strtoupper($this->title); //or anything else
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Article;
use App\Entity\Newsletter;
use App\Entity\Category;
use Knp\Component\Pager\PaginatorInterface;
use Doctrine\Persistence\ManagerRegistry as PersistenceManagerRegistry; 

class ArticleController extends AbstractController
{
    #[Route('/article/{id}', name: 'article')]
    public function index(Request $request,
        EntityManagerInterface $entityManager,
        PersistenceManagerRegistry $doctrine,
        PaginatorInterface $paginator): Response
    {

        $idArticle = $request->get("id");
        $article = $doctrine->getRepository(Article::class)->find($idArticle);

        // récupérer les commentaires valides pour cet article
        $comments = $entityManager->getRepository(Comment::class)->findAllValidComments($idArticle);
        
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $comment->setArticle($article);
            $comment->setDate(new \DateTime);
            $comment->setUser($this->getUser());
            $comment->setIsValid(false);

            $entityManager->persist($comment);
            $entityManager->flush();

            // réinitialiser le formulaire
            $comment = new Comment();
            $form = $this->createForm(CommentType::class, $comment);

            $this->addFlash('secondary', 'Votre commentaire sera validé prochainement pour publication !');
            
        }

        if (!empty($request->request->get('newsletter'))) {
            
            $email = strtolower($request->request->get('newsletter'));
            $frequence = $request->request->get('frequence');

            $entityManager = $doctrine->getManager();
            $newsletter = new Newsletter();
            $newsletter->setEmail($email);
            $newsletter->setFrequence($frequence);

            $entityManager->persist($newsletter);
            $entityManager->flush();

            $this->addFlash('secondary', 'Vous avez bien été inscrit à notre newsletter !');

        }


        $relatedArticles = $doctrine->getRepository(Article::class)->findRelatedArticles($article->getCategory(), $idArticle);

        $relatedArticles = $paginator->paginate(
            $relatedArticles, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3 /*limit per page*/
        );

        return $this->render('article/index.html.twig', [
            'article' => $article,
            'relatedArticles' => $relatedArticles,
            'categorySelected' => $article->getCategory(),
            'form_comment' => $form,
            'comments' => $comments
        ]);
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Article;
use App\Entity\Category;
use App\Entity\Newsletter;
use Knp\Component\Pager\PaginatorInterface;

use Doctrine\Persistence\ManagerRegistry as PersistenceManagerRegistry; 


class ArticlesController extends AbstractController
{
    #[Route('/articles/{id}', name: 'articles')]
    public function index(Request $request, PersistenceManagerRegistry $doctrine, PaginatorInterface $paginator): Response
    {

        if (!empty($request->request->get('newsletter'))) {
            
            $email = strtolower($request->request->get('newsletter'));
            $frequence = $request->request->get('frequence');

            $entityManager = $doctrine->getManager();
            $newsletter = new Newsletter();
            $newsletter->setEmail($email);
            $newsletter->setFrequence($frequence);

            $entityManager->persist($newsletter);
            $entityManager->flush();

            $this->addFlash('secondary', 'Vous avez bien été inscrit à notre newsletter !');

        }

        $idCategory = $request->get("id");
        $articles = $doctrine->getRepository(Article::class)->findByCategory($idCategory);
        $category = $doctrine->getRepository(Category::class)->find($idCategory);

        $articles = $paginator->paginate(
            $articles, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            5 /*limit per page*/
        );

        
        return $this->render('articles/index.html.twig', [
            'listArticles' => $articles,
            'categorySelected' => $category,
            'searchSelect' => null
        ]);
    }

    #[Route('/articles/search/{subject}', name: 'articles_by_subjects')]
    public function articlesBySubject(Request $request, PersistenceManagerRegistry $doctrine, PaginatorInterface $paginator): Response
    {

        if (!empty($request->request->get('newsletter'))) {
            
            $email = strtolower($request->request->get('newsletter'));
            $frequence = $request->request->get('frequence');

            $entityManager = $doctrine->getManager();
            $newsletter = new Newsletter();
            $newsletter->setEmail($email);
            $newsletter->setFrequence($frequence);

            $entityManager->persist($newsletter);
            $entityManager->flush();

            $this->addFlash('secondary', 'Vous avez bien été inscrit à notre newsletter !');

        }

        $subject = strtolower($request->get("subject"));
        $articles = $doctrine->getRepository(Article::class)->findBySearch($subject);
        
        $articles = $paginator->paginate(
            $articles, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            5 /*limit per page*/
        );

        return $this->render('articles/index.html.twig', [
            'listArticles' => $articles,
            'searchSelect' => $subject,
            'categorySelected' => null

        ]);
    }

    #[Route('/articles', name: 'all_articles')]
    public function allArticles(Request $request, PersistenceManagerRegistry $doctrine, PaginatorInterface $paginator): Response
    {

        if (!empty($request->request->get('newsletter'))) {
            
            $email = strtolower($request->request->get('newsletter'));
            $frequence = $request->request->get('frequence');

            $entityManager = $doctrine->getManager();
            $newsletter = new Newsletter();
            $newsletter->setEmail($email);
            $newsletter->setFrequence($frequence);

            $entityManager->persist($newsletter);
            $entityManager->flush();

            $this->addFlash('secondary', 'Vous avez bien été inscrit à notre newsletter !');

        }

        $articles = $doctrine->getRepository(Article::class)->findAll();

        $articles = $paginator->paginate(
            $articles, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            5 /*limit per page*/
        );

        
        return $this->render('articles/index.html.twig', [
            'listArticles' => $articles,
            'categorySelected' => null,
            'searchSelect' => null
        ]);
    }

}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block meta_description %} {{ article.chapo }} {% endblock %}
{% block meta_title %} {{ article.title }} {% endblock %}
{% block title %} {{ article.title }} {% endblock %}

{% form_theme form_comment 'bootstrap_5_layout.html.twig' %}


{% block metas %} 

{# TWITTER #}
<meta name="twitter:card" content="photo" />
<meta name="twitter:site" content="@lareponsenumerique" />
<meta name="twitter:creator" content="@lareponsenumerique" />
<meta name="twitter:image:alt" content="{{article.title}}">
<meta name="twitter:title" content="{{article.title}}">
<meta name="twitter:description" content="{{article.chapo}}">
<meta name="twitter:image" content="https://www.lareponsenumerique.fr/{{article.picture}}">
<meta name="twitter:domain" content="https://www.lareponsenumerique.fr">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.lareponsenumerique.fr/article/{{article.id}}">
<meta property="og:title" content="{{article.title}}">
<meta property="og:description" content="{{article.chapo}}">
<meta property="og:image" content="https://www.lareponsenumerique.fr/{{article.picture}}">

{# LINKEDIN #}
<meta name="author" content="{{article.author}}">
<meta name="publish_date" property="og:publish_date" content="{{ article.date|date('Y-m-d') }}">

{% endblock %}

{% block body %}

{# ARTICLE #}

    {{ render(controller('App\\Controller\\NavBarController::index')) }}

    <div class="global-layout">


        {# PROGRESSION LECTURE ARTICLE #}
        <div class="col-12 progression">
            <div class="progression-value" style="width: 0.211765%;"> </div>
        </div>

        {% include 'messages.html.twig' %}


        <div id="article" class="row py-5">

            {% include 'ariane.html.twig' %}
            
            {% include 'messages.html.twig' %}

            <div class="row col-8 mx-auto justify-content-center flex-column align-items-center detail-article">

                <h1 class="text-center mb-5 text-less-grey"> {{ article.title }} </h1>

                <p class="text-center mb-5 text-grey"> {{article.chapo}} </p>
                
                <div class="d-flex justify-content-center mb-5" data-bs-toggle="modal" data-bs-target="#article-social-networks">>
                    <button class="btn btn-secondary text-less-grey py-2"> PARTAGER L'ARTICLE </button>
                </div>
            
                <div class="d-flex justify-content-center author text-grey mb-5">
                    <a aria-label="Accéder à la page 'Qui sommes-nous?' de l'Académie WS"  href="{{article.authorWebsite}}" class="byline fst-italic">{{article.author}} </a>&nbsp;-&nbsp;<span class="posted-on fst-italic"> Publié le 
                    <time class="entry-date published updated" datetime="2023-01-10T11:16:57+01:00"> {{ article.date |date("d/m/Y") }}</time></span>
                </div>

                <div class="d-flex flex-column">
                    <img title="{{ article.title }}" alt="{{ article.title }}" width="100%" src="{{ asset('' ~ article.picture)}}" >
                    <p class="pt-2 m-0 text-grey legend fst-italic"> {{ article.legendMainPicture }} © Académie WS - <a class="text-secondary" href="https://academiews.fr"> academiews.fr </a> </p>
                </div>

                <div class="article-content my-5">

                    {{ article.description|raw }}

                    <h2 class="text-secondary"> En savoir plus </h2>
                    <p class="fst-italic"> Envie d'en savoir plus sur le sujet? retrouvez l'intégralité de la formation vidéo liée à la thématique
                        <a href="https://academiews.fr/course/{{article.relatedCourse}}" title="{{article.catchPhrase}} - Académie WS ">'{{article.catchPhrase}}'</a>
                    sur le site de <a href="https://academiews.fr/" title="Académie WS "> l'Académie WS ! </a>
                    </p>
                </div>
                
            </div>

             {% if app.user %}
                <div class="col-md-8 mx-auto">
                    {{ form(form_comment) }}
                </div>
            {% endif %}

                <div class="col-md-8 mx-auto">
                    <h5 class="text-less-grey "> Commentaires : </h5>
                    {% for comment in comments %}
                        <div class="comment p-3 my-3">

                            <span class="text-grey fst-italic"> {{ comment.user.firstName }} </span>

                            <p class="text-less-grey"> {{ comment.comment }} </p>
                            <span class="text-grey"> {{ comment.date|date('d-m-Y') }} </span>


                        </div>
                    {% endfor %}
                </div>

            {{ render(controller('App\\Controller\\ThemesController::index')) }}

            <div class="row mx-auto related-subjects">

                <div class="d-flex flex-wrap col-8 mx-auto py-5">

                    <span class="text-less-grey fw-bold">Sujets liés :</span>

                    <ul class="d-flex ms-2">

                    {% for relatedSubject in article.relatedSubjects %}
                        <div class="d-flex">
                            <li> 
                                <a aria-label="Retrouvez nos articles liés au sujet intitulé '{{ relatedSubject }}'" class="text-secondary" href="{{ path('articles_by_subjects', {subject:relatedSubject}) }}"> {{relatedSubject}} </a>
                            </li> 
                            <span class="text-less-grey px-2"> / <span>
                        </div>
                    {% endfor %}

                    </ul>
                </div>

                <div class="d-flex mx-auto col-8 mb-5" data-bs-toggle="modal" data-bs-target="#article-social-networks">>
                    <button class="btn btn-secondary text-less-grey py-2"> PARTAGER L'ARTICLE </button>
                </div>

            </div>


            <div class="row col-md-12 mx-auto justify-content-center" id="other-articles">

                <div class="col-8">

                    <h2 class="my-5 text-less-grey"> Consultez des articles similaires </h2>

                    <div class="row list-related-articles">

                        {% for relatedArticle in relatedArticles %}

                            {# un article #}
                            <div class="col-sm-12 col-md-4 px-2 card-articles">
                                <div class="col-md-12 d-flex flex-column article p-4 align-items-start form-shadow-white">

                                    <div class="d-flex align-items-start">

                                        <img title="{{ relatedArticle.title }}" alt="{{ relatedArticle.title }}" width="150px" src="{{ asset('' ~ relatedArticle.picture)}}" >

                                        <div class="d-flex flex-column">
                                            <p class="text-less-grey ps-2 my-0"> {{ relatedArticle.category.name }} </p>
                                            <p class="text-grey ps-2 my-0"> {{ relatedArticle.author }} </p>
                                        </div>

                                    </div>

                                    <p class="text-grey my-4">
                                        {{ relatedArticle.chapo[:150] ~ '...'  }}
                                    </p>

                                    <a aria-label="Accéder à l'article intitulé '{{ relatedArticle.title }}' " href="{{ path('article', {id:relatedArticle.id}) }}" class="py-3 btn btn-outline-secondary text-white text-grey">Accéder à l'article</a>

                                </div>
                            </div>

                        {% endfor %}

                    </div>

                    <div class="pt-5 col-md-12 navigation">
                        {{ knp_pagination_render(relatedArticles) }}
                    </div>  
                    
                </div>

            </div>

            {# newsletter #}

            <div class="row mx-auto my-5 px-5 pt-5" id="newsletter">

                <div class="col-md-8">
                    <h2 class="text-less-grey pt-5 pb-3"> Recevez par email toute l’actualité du digital </h2>
                        <form method="POST">
                            <div class="d-flex pb-3">
                                <input type="text" placeholder="Entrez votre adresse email" class="col-8 newsletter px-5 py-3" name="newsletter" >
                                <input class="text-less-grey px-3 bg-secondary" type="submit" value="JE M'INSCRIS">
                            </div>
                            <div class="d-flex pb-3">
                                <div class="mx-3">
                                    <input type="radio" id="test1" value="1" name="frequence" checked>
                                    <label class="text-grey" for="test1">Chaque matin</label>
                                </div>
                                <div class="mx-3">
                                    <input type="radio" id="test2" value="2" name="frequence">
                                    <label class="text-grey" for="test2">Chaque semaine</label>
                                </div>
                            </div>

                            <p class="col-12 col-md-7 text-grey fst-italic"> En cliquant sur "S'inscrire", vous acceptez les CGU ainsi que notre politique de confidentialité décrivant la finalité des traitements de vos données personnelles. </p>

                        </form>

                </div>

                <div class="d-flex col-md-4 align-items-end illustration-part">
                    <img alt="Abonnez-vous à la newsletter de la réponse numérique" title="Newsletter de la réponse numérique" class="w-100" src="{{ asset('newsletter.webp') }}">
                </div>

            </div>

            {% include 'footer.html.twig' %}

        </div>
    </div>

    {# 

        MODAL RÉSEAUX SOCIAUX
    
     #}

    <div class="modal fade" id="article-social-networks" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Partager l'article</h1>
            <button type="button" class="btn-close btn-secondary" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body p-4">
            <ul class="d-flex justify-content-around"> 
                <li>
                    <a aria-label="Partagez l'article intitulé '{{article.title}}' sur Twitter." href="https://twitter.com/share?url=https://www.lareponsenumerique.fr/article/{{article.id}}&via=lareponsenumerique&text={{article.title}}"
                    onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
                        target="_blank" title="Share on Twitter">
                        <i style="color:#1DA1F2;height:2rem" class="fa-brands fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a aria-label="Partagez l'article intitulé '{{article.title}}' sur Linkedin." href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.lareponsenumerique.fr/article/{{article.id}}"
                        onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
                        target="_blank" title="Share on Linkedin">  
                        <i style="color:#1DA1F2;height:2rem" class="px-2 fa-brands fa-linkedin"></i>
                    </a>
                </li>
                <li>
                    <a aria-label="Partagez l'article intitulé '{{article.title}}' sur Facebook." href="https://www.facebook.com/sharer/sharer.php?u=https://www.lareponsenumerique.fr/article/{{article.id}}"
                        onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
                        target="_blank" title="Share on Facebook">                                    
                        <i style="color:#3b5998;height:2rem" class="fa-brands fa-facebook"></i>
                    </a>
                </li>
                <li>
                    <a aria-label="Partagez l'article intitulé '{{article.title}}' par email." href="mailto:?subject=Académie WS - {{ article.title }}&amp;body=La Rubrique du numérique - {{ article.chapo }} - https://www.lareponsenumerique.fr/{{article.id}}" title="Share by Email"
                        onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
                        target="_blank" title="Share by email">                                    
                        <i style="height:2rem" class="text-secondary fa-solid fa-envelope"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="d-flex px-3 pb-3">
            <input type="text" class="px-5 py-3 w-100" id="clipboard" value="https://www.academiews.fr/article/{{article.id}}" >
            <button aria-label="Copiez le lien de l'article intitulé '{{article.title}}' sur Linkedin." class="text-less-grey px-3 bg-secondary btn-clipboard">COPIER</button>
        </div>
        </div>
    </div>
    </div>





{% endblock %}